---
- name: Test archive module from community.general
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create a sample file
      copy:
        dest: /home/aap/hello.txt
        content: "Hello from AAP!"

    - name: Archive the file into /tmp/hello.tar.gz
      community.general.archive:
        path: /home/aap/hello.txt
        dest: /home/aap/hello.tar.gz
      delegate_to: localhost
